#!/bin/sh


export PATH="$HOME/.local/bin":$PATH
export PATH=$HOME/bin:$PATH
export PATH="/usr/local/sbin:$PATH"
# Created by `pipx` on 2022-04-16 15:51:22
export PATH="$PATH:/Users/onoma/Library/Python/3.8/bin"
# Created by `pipx` on 2022-04-16 15:51:22
export PATH="$PATH:/Users/onoma/.local/bin"
export PATH="$HOME/.ghcup/bin":$PATH

export EDITOR=nvim
export VISUAL=nvim
export CLICOLOR=1




export MANWIDTH=999


# Prefer US English and use UTF-8.
export LANG='en_US.UTF-8';
export LC_ALL='en_US.UTF-8'

# Highlight section titles in manual pages.
export LESS_TERMCAP_md="${yellow}";

# Don’t clear the screen after quitting a manual page.
export MANPAGER='less -X'



# export PATH=$HOME/.cargo/bin:$PATH
# export PATH=$HOME/.local/share/go/bin:$PATH
# export GOPATH=$HOME/.local/share/go
# export PATH=$HOME/.fnm:$PATH
# export PATH="$PATH:./node_modules/.bin"
# eval "$(fnm env)"
# eval "$(zoxide init zsh)"
# eval "`pip completion --zsh`"


# >>> conda initialize >>>
# !! Contents within this block are managed by 'conda init' !!
# __conda_setup="$("$HOME/.miniconda/bin/conda" 'shell.zsh' 'hook' 2> /dev/null)"
# if [ $? -eq 0 ]; then
#     eval "$__conda_setup"
# else
#     if [ -f "$HOME/.miniconda/etc/profile.d/conda.sh" ]; then
#         . "$HOME/.miniconda/etc/profile.d/conda.sh"
#     else
#         export PATH="$HOME/.miniconda/bin:$PATH"
#     fi
# fi
# unset __conda_setup
# <<< conda initialize <<<
